### ISSUE TITLE
Move as much code as possible to Pipeline and Liblouis 

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-nota#25]
### Braille translation

- [ ] Handling of `text-transform: uncontracted` in `NotaTranslator` can be dropped because it is now handled in standard Pipeline.
- [ ] Emphasis should be handled by Liblouis. I'm not sure why this is not already the case. Related: https://github.com/snaekobbi/pipeline-mod-nota/issues/8.
- [ ] Language should be handled in CSS. See https://github.com/snaekobbi/pipeline-mod-nota/issues/7. The required CSS seems already added, but there is also still XSLT code present.
- [ ] If the above items have been solved, `block-translate.xsl` and `NotaTranslator` can be removed.

### Style sheets

- [ ] Certain bits of code that are not specific to Nota (if generalized) could be moved to Pipeline:
  - [ ] Tables: see [NLB](https://github.com/nlbdev/pipeline/issues/225)
    - There could also be an option to create multiple version of a table, with different layouts. Upon checking the result the user can than decide which variant is the best. (This is currently done in duplicate-tables.xsl.)
  - [ ] Notes: see [NLB](https://github.com/nlbdev/pipeline/issues/225)
    - Noterefs are currently replaced with the note elements that they reference (mark-noterefs.xsl), so that the `::footnote-call` approach can be used to lay out the notes. But there also exists an alternative to lay out notes (with `::alternate` and `target-content()`). If possible we should use this simpler alternative (requires no XSLT).
  - [ ] Table of contents: see [SBS](https://github.com/sbsdev/pipeline-mod-sbs/issues/75)
  - [ ] Images: see [NLB](https://github.com/nlbdev/pipeline/issues/225)
  - [ ] Print page break indication: see [NLB](https://github.com/nlbdev/pipeline/issues/225)
